version: '2'
services:
  drone-server:
    image: drone/drone
    ports:
      - 8000:80
    volumes:
      - /var/lib/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone-tree-config
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=192.168.166.89:8000
      - DRONE_GITLAB=true
      - DRONE_GITLAB_SERVER=http://192.168.166.89:5080/
      - DRONE_GITLAB_CLIENT_ID=a1d0cd7ef825ebd3cff104c6b9bf5c1b2bfb5ae49f45a34f2f2e01a1b5de1092
      - DRONE_GITLAB_CLIENT_SECRET=25263abff3677a0b0444c3c5fc6918045181a9dad98a9d87cf1424e431f8d056
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_SECRET=ea81f4b1d0856d4cdf8fd6440945b50c
      - DRONE_RUNNER_CAPACITY=2

      - DRONE_YAML_ENDPOINT=http://drone-tree-config:3000
      - DRONE_YAML_SECRET=<08e19d9cbac38a2a51df88fd569f7647

  drone-tree-config:
    image: bitsbeats/drone-tree-config
    environment:
      - PLUGIN_DEBUG=true
      - PLUGIN_CONCAT=true
      - PLUGIN_FALLBACK=true
      - PLUGIN_SECRET=<08e19d9cbac38a2a51df88fd569f7647
      - GITLAB_TOKEN=wTpMwDv6t4AyR2VobFzJ
    restart: always